project:
  type: website

website:
  search: false
  title: "Jonathan Barnes"
  
  navbar:
    left:
      - href: ./Sections/Resume/Resume.qmd
        text: Resume
      - href: ./Sections/Portfolio/Portfolio.qmd
        text: Portfolio
      - href: ./Sections/Projects/CurrentProjects.qmd
        text: Current Projects
      - text: Other Work
        menu: 
          - href: ./Sections/Projects/ProjectsTest.qmd
            text: All Projects
          - href: ./Sections/Cat Photos/Cats.qmd
            text: Shiny Applications
          - href: ./Sections/ReferenceGuides/References.qmd
            text: Reference Documents
          - href: ./Sections/ListofHelpfulThings.qmd
            text: Recomended Resources
    right:
      - icon: info
        href: about.qmd
        text: About Me
    search: false
      
  page-footer:
      border: true
      background: light
      center:
        - icon: github
          href: https://github.com/jonathanmbarnes
        - icon: linkedin
          href: https://www.linkedin.com/in/jonathanbarnes516
          
      right:
        - href: ./Sections/Cat Photos/Cats.qmd
          text: Cat Photos

format:
  html:
    theme: 
      light: sandstone
      dark: superhero
    mainfont: Aptos
    monofont: Museo Sans
    css: styles.css
    toc: true
    max-width: 1700px
    page-layout: full
    
execute:
  freeze: auto

editor: visual

