project:
  type: website

website:
  title: "Jonathan Barnes"
  navbar:
    left:
      - href: ./Sections/Resume/Resume.qmd
        text: Resume
      - href: ./Sections/Portfolio/Portfolio.qmd
        text: Portfolio
      - href: ./Sections/Projects/CurrentProjects.qmd
        text: Current Projects
      - text: Other Work
        menu: 
          - href: ./Sections/Projects/ProjectsTest.qmd
            text: All Projects
          - href: ./Sections/Cat Photos/Cats.qmd
            text: Shiny Applications
          - href: ./Sections/ReferenceGuides/References.qmd
            text: Reference Documents
    right:
      - href: ./Sections/Cat Photos/Cats.qmd
        text: Cat Photos
      - icon: info
        href: about.qmd
        text: " "
      
  page-footer:
      border: true
      background: light
      center:
        - icon: github
          href: https://github.com/jonathanmbarnes
        - icon: linkedin
          href: https://www.linkedin.com/in/jonathanbarnes516

format:
  html:
    theme: 
      light: sandstone
      dark: superhero
    css: styles.css
    toc: true
    mainfont: Aptos
    monofont: Museo Sans
    
execute:
  freeze: auto

editor: visual

