project:
  type: website

website:
  title: "Jonathan Barnes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ./Resume/Resume.qmd
        text: Resume
      - href: ./Portfolio/PortfolioTest.qmd
        text: Portfolio
    right:
      - href: ./Cat Photos/Cats.qmd
        text: Cat Photos
      - about.qmd
      
  page-footer:
      center:
        - icon: github
          text: Github
          href: https://github.com/jonathanmbarnes
        - icon: linkedin
          text: Linkedin
          href: https://www.linkedin.com/in/jonathanbarnes516

format:
  html:
    theme: 
      light: sandstone
      dark: superhero
    css: styles.css
    toc: true
    mainfont: Aptos
    monofont: Calibri
    
execute:
  freeze: auto

editor: visual

